{% set name = "gif" %}
{% set version = "22.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gif-{{ version }}.tar.gz
  sha256: ab37620cbf3b5cb1eb2cca0676577a96e030f0bfb1ff2dba06d85aaf383e2e44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=62.1.0
  run:
    - python >=3.9
    - matplotlib-base >=3.5,<4.0
    - pillow >=9.1

test:
  imports:
    - gif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxhumber/gif
  summary: The matplotlib Animation Extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
