{% set name = "gif" %}
{% set version = "23.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gif-{{ version }}.tar.gz
  sha256: 9e4ef83620277dd7e81b016931684b544e5751c17d6db18b820399c7c74e04ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=62.1.0
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5,<4.0
    - pillow >=9.1

test:
  imports:
    - gif
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maxhumber/gif
  summary: The matplotlib Animation Extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
